### ISSUE TITLE
RadialMenuWidtget v1 on Tablet

### ISSUE THREAD

**Issue by hpardora** [strider2023/Radial-Menu-Widget-Android#3]
hi, i'm testing your library on a Tablet and i found a problem.. the max_x where the library draw the menu is about 580px for portrait and landscape.

These is a problem or i have a mistake in the code?

thx!

**Comment by ipip2005** [comment]
@hpardora 
the issue bothered me too,
as far as i see, the RadialMenuWidget was added to the view by using popupwindow as a transition view.
in RadialMenuHelper.java, I simply changed
window.setWidth(WindowManager.LayoutParams.WRAP_CONTENT);
to
window.setWidth(WindowManager.LayoutParams.MATCH_PARENT);
the issue was gone and there is no other problem so far
hope it works for you

**Comment by Hertog-PJ** [comment]
Did you also experience problems that the radial menu is getting cutoff at some imaginary vertical line somewhere at 3/4 of the screen (portrait mode)? The cut off line seems to be around 1/2 of the screen in landscape mode.
